name: "github-actions-Var"

# Configure which branch that will trigger Eggplant DAI GitHub Action
# on:
#  push:
#    branches:
#      - main 
#  pull_request:
#    branches:
#      - main

jobs:
  Run-DAI-Test-Configuration:
    strategy: # Optional configuration by using matrix strategy
      max-parallel: 1 # To set the maximum number of jobs that can run simultaneously 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Operating support by Eggplant DAI GitHub Action
    runs-on: ${{ matrix.os }} # Provide OS matrix
    name: Run Test Configuration
    steps:
      - run: echo "Trigger event.. ${{ github.event_name }}. Runner OS.. ${{ runner.os }}."
     - name: Eggplant Runner
  uses: keysight-eggplant/eggplant-github-action@v1.0.1
 with:
       serverURL: "http://localhost:8000/" # Required. Details below
          testConfigID: "408caa2b-0bb9-4105-8fe8-f9834e357877" # Required. Details below
      clientSecret: "5ae7b3b4-22ed-420e-b156-4878ddb0f430" # Required. Details below
